server:
  port: 8762
  shutdown: graceful

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: planverse-dev
          uri: lb://planverse-dev
          predicates:
            - Path=/planverse-dev/**
        - id: planverse-main
          uri: lb://planverse
          predicates:
            - Path=/planverse/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://${spring.security.user.name}:${spring.security.user.password}@eureka.seoeungi.work/eureka
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, refresh